[package]
name = "xplorer-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
xplorer-core = { path = "../xplorer-core" }
eframe = { version = "0.31", default-features = true }
egui_extras = { version = "0.31", features = ["all_loaders"] }
egui-phosphor = { version = "0.9", default-features = true }
egui_dock = "0.16"
rfd = "0.15"
egui-notify = "0.19"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
dirs = "5.0"
chrono = { version = "0.4", features = ["serde"] }
arboard = "3"
notify = "7"
notify-debouncer-full = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
